#name: DetaApp (TEST) — CI
name: test
on:
  pull_request:
    branches:
      - dev
      - main
    #paths:
    #  - "detaApp/src**"
  push:
    branches:
      - dev
      - main
    #paths:
    #  - "detaApp/src**"
jobs:
  Setup-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"
      - name: Installing dependencies
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
  Setup-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "detaApp/package-lock.json"
      - name: Installing dependencies
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
  Test:
    runs-on: ubuntu-latest
    needs: Setup-docs
    steps:
      - name: foo
        run: "ls -al && ls detaApp && cd detaApp && space -h"
  Lint:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: foo
        run: "pwd && ls detaApp"
  Build:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Build docs
        run: |
          cd docs
          npm run build
      - name: Build frontend
        run: |
          cd detaApp
          npm run build
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Push code
        run: space push
      - name: Create release
        run: space release --id foobar --latest --version v0.0.2
  Notify:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: foo
        run: "echo todo"