#name: DetaApp (TEST) — CI
name: test
on:
  pull_request:
    branches:
      - dev
      - main
    #paths:
    #  - "detaApp/src**"
  push:
    branches:
      - dev
      - main
    #paths:
    #  - "detaApp/src**"
jobs:
  Check-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "detaApp/package-lock.json"
      - name: Install dependencies
        working-directory: detaApp
        run: npm i
      - name: Run check
        run: |
          npm run check
  Test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "detaApp/package-lock.json"
      - name: Install dependencies
        working-directory: detaApp
        run: npm i
      - name: Run tests
        working-directory: detaApp
        run: |
          npm run test
  Lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "detaApp/package-lock.json"
      - name: Install dependencies
        working-directory: detaApp
        run: npm i
      - name: Run lint
        working-directory: detaApp
        run: |
          npm run lint

  Build-frontend:
    runs-on: ubuntu-latest
    needs: ["Check-frontend", "Test-frontend", "Lint-frontend"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "detaApp/package-lock.json"
      - name: Install dependencies
        working-directory: detaApp
        run: npm i
      - name: Run build
        working-directory: detaApp
        run: |
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: frontend-build-bundle
          path: |
            detaApp/package-lock.json
            detaApp/package.json
            detaApp/bundled
  Build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"
      - name: Install dependencies
        working-directory: docs
        run: npm i
      - name: Run build
        working-directory: docs
        run: |
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: docs-build-bundle
          path: |
            docs/package-lock.json
            docs/package.json
            docs/out

  Deploy:
    runs-on: ubuntu-latest
    needs: ["Build-frontend", "Build-docs"]
    steps:
      - name: Install dependencies
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
      - name: Authenticate Deta CLI
        run: ls -al
      - name: Download docs build artifacts
        uses: actions/download-artifact@v3
        with:
          name: docs-build-bundle
          path: docs/
      - name: Download frontend build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build-bundle
          path: detaApp/
      - name: foo
        run: |
          ls -al
          echo docs
          ls docs
          echo detaApp
          ls detaApp
          echo cli
          space -h

  # Setup-docs:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: Setup NodeJS
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #         cache-dependency-path: "docs/package-lock.json"
  #     - name: Install other dependencies
  #       run: |
  #         curl -fsSL https://get.deta.dev/space-cli.sh | sh
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: docs-setup
  #         path: docs
  # Setup-frontend:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: Setup NodeJS
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #         cache-dependency-path: "detaApp/package-lock.json"
  #     - name: Install other dependencies
  #       run: |
  #         curl -fsSL https://get.deta.dev/space-cli.sh | sh
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: frontend-setup
  #         path: detaApp
  # Test-frontend:
  #   runs-on: ubuntu-latest
  #   needs: Setup-frontend
  #   steps:
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: frontend-setup
  #         path: detaApp
  #     - name: foo
  #       run: |
  #         ls -al
  #         space -h
  # Lint-frontend:
  #   runs-on: ubuntu-latest
  #   needs: Test-frontend
  #   steps:
  #     - name: foo
  #       run: pwd
  # Build-docs:
  #   runs-on: ubuntu-latest
  #   needs: Setup-docs
  #   steps:
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: docs-setup
  #         path: docs
  #     - name: Build docs
  #       run: |
  #         cd docs
  #         npm run build
  # Build-frontend:
  #   runs-on: ubuntu-latest
  #   needs: Lint-frontend
  #   steps:
  #     - name: Build docs
  #       run: |
  #         cd docs
  #         npm run build
  #     - name: Build frontend
  #       run: |
  #         cd detaApp
  #         npm run build
  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: ["Build-docs", "Build-frontend"]
  #   steps:
  #     - name: Push code
  #       run: space push
  #     - name: Create release
  #       run: space release --id foobar --latest --version v0.0.2
  # Notify:
  #   runs-on: ubuntu-latest
  #   needs: Deploy
  #   steps:
  #     - name: foo
  #       run: "echo todo"